- name: Create Azure VM
  hosts: localhost
  connection: local

  vars:
    myResourceGroup: ansible
    myVM: ansible-prod-node
    
  tasks:

  - name: Start Minikube
    command: minikube start --vm-driver=virtualbox
    become: true

  - name: Deploy
    command: kubectl apply -f home/cwuser/deployment.yml

  - name: Service
    command: kubectl apply -f home/cwuser/service.yml

